//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOSUDUNGTHUOC
    {
        public int MaBaoCaoSuDungThuoc { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> SoLanDung { get; set; }
        public Nullable<int> TongSoLuongDaDung { get; set; }
        public Nullable<int> MaThuoc { get; set; }
    
        public virtual THUOC THUOC { get; set; }
    }
}
