//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BCDT
    {
        public int CTBCDT_ID { get; set; }
        public int MaBCDT { get; set; }
        public int SoHD { get; set; }
        public Nullable<int> SoBenhNhan { get; set; }
        public Nullable<double> DoanhThu { get; set; }
        public Nullable<double> TiLe { get; set; }
    
        public virtual BAOCAODOANHTHU BAOCAODOANHTHU { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
