//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int SoHD { get; set; }
        public double TienKham { get; set; }
        public Nullable<double> TienThuoc { get; set; }
        public double TongTien { get; set; }
        public Nullable<int> MaBN { get; set; }
        public Nullable<int> MaPKB { get; set; }
        public string TrangThai { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        public virtual PHIEUKHAMBENH PHIEUKHAMBENH { get; set; }
    }
}
