//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateClinic.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYPHONGMACHTUEntities : DbContext
    {
        public QUANLYPHONGMACHTUEntities()
            : base("name=QUANLYPHONGMACHTUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BACSI> BACSI { get; set; }
        public virtual DbSet<BAOCAODOANHTHU> BAOCAODOANHTHU { get; set; }
        public virtual DbSet<BAOCAOSUDUNGTHUOC> BAOCAOSUDUNGTHUOC { get; set; }
        public virtual DbSet<BENHNHAN> BENHNHAN { get; set; }
        public virtual DbSet<CACHDUNG> CACHDUNG { get; set; }
        public virtual DbSet<CT_BCDT> CT_BCDT { get; set; }
        public virtual DbSet<CT_PKB> CT_PKB { get; set; }
        public virtual DbSet<CT_PNT> CT_PNT { get; set; }
        public virtual DbSet<CHUCNANG> CHUCNANG { get; set; }
        public virtual DbSet<DVT> DVT { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<LOAIBENH> LOAIBENH { get; set; }
        public virtual DbSet<LOAITHUOC> LOAITHUOC { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNG { get; set; }
        public virtual DbSet<NHOMNGUOIDUNG> NHOMNGUOIDUNG { get; set; }
        public virtual DbSet<PHIEUKHAMBENH> PHIEUKHAMBENH { get; set; }
        public virtual DbSet<PHIEUNHAPTHUOC> PHIEUNHAPTHUOC { get; set; }
        public virtual DbSet<THAMSO> THAMSO { get; set; }
        public virtual DbSet<THUOC> THUOC { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYEN { get; set; }
    }
}
