//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAPTHUOC
    {
        public int SoPhieuNhap { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public double TongTien { get; set; }
    }
}
