//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUKHAMBENH
    {
        public int MaPKB { get; set; }
        public System.DateTime NgayKham { get; set; }
        public int MaLoaiBenh { get; set; }
        public Nullable<int> MaBS { get; set; }
        public string TrieuChung { get; set; }
        public string MaBN { get; set; }
    
        public virtual BACSI BACSI { get; set; }
        public virtual BENHNHAN BENHNHAN { get; set; }
        public virtual LOAIBENH LOAIBENH { get; set; }
    }
}
