//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUOC1
    {
        public int MaThuoc { get; set; }
        public int MaLoaiThuoc { get; set; }
        public string TenThuoc { get; set; }
        public double DonGia { get; set; }
        public int MaDVT { get; set; }
        public int MaCachDung { get; set; }
    
        public virtual CACHDUNG CACHDUNG { get; set; }
        public virtual DVT DVT { get; set; }
        public virtual LOAITHUOC LOAITHUOC { get; set; }
    }
}
